name = "Better Content Modpack"
version = "Build 390"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c796f28ff967dfca2339f7a50db28bbb3cfacfc824e76d9587daa88ea77787dd"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
