name = "Better Content Modpack"
version = "Build 345"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f10f38f41229479c723defb090215c1fc696535e6962a24d435792e30a1001c8"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
