name = "Better Content Modpack"
version = "Build 229"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a051e661175105cbe921059ada0d70cfd10fcfe8b2e2096178a3d3db5ea23f80"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
