# Goety architecture supports adjoining Goety pieces across broad spans.
#A list of block IDs and tags that should be affected by this definition.
#Entries can be supplied in the below formats:
#	Namespaces:   '<minecraft>'
#	Tags:         '#forge:stone'
#	IDs:          'minecraft:stone'
Blocks = [
	"goety:blue_siltstone_pillar",
	"goety:bottom_soiled_end_basalt",
	"goety:chiseled_siltstone",
	"goety:chiseled_siltstone_bricks",
	"goety:cobbled_chorus_grass_block",
	"goety:cobbled_siltstone",
	"goety:dirty_chiseled_siltstone",
	"goety:dirty_cobbled_end_stone",
	"goety:dirty_cobbled_end_stone_heavy",
	"goety:dirty_cobbled_siltstone",
	"goety:dirty_end_basalt",
	"goety:dirty_end_rock",
	"goety:dirty_ominous_stone",
	"goety:dirty_ominous_stone_bricks",
	"goety:dirty_ominous_stone_bricks_heavy",
	"goety:dirty_ominous_stone_bricks_slight",
	"goety:dirty_ominous_stone_pavement",
	"goety:dirty_ominous_stone_pavement_heavy",
	"goety:dirty_ominous_stone_slight",
	"goety:dirty_ominous_stone_tiles",
	"goety:dirty_ominous_stone_tiles_heavy",
	"goety:dirty_ominous_stone_tiles_slight",
	"goety:dirty_siltstone",
	"goety:dirty_siltstone_heavy",
	"goety:grassy_cobbled_end_stone",
	"goety:grassy_end_basalt",
	"goety:grassy_end_rock",
	"goety:grassy_end_rock_bricks",
	"goety:grassy_end_stone_bricks",
	"goety:grassy_end_stone_bricks_heavy",
	"goety:grassy_end_stone_tiles",
	"goety:grassy_purpur_block",
	"goety:grassy_smooth_end_stone",
	"goety:grassy_smooth_end_stone_heavy",
	"goety:green_siltstone_pillar",
	"goety:muddy_smooth_end_stone",
	"goety:red_siltstone_pillar",
	"goety:silt_highrock",
	"goety:silt_jade_tiles",
	"goety:silt_marble",
	"goety:silt_marble_heavy",
	"goety:silt_marble_slight",
	"goety:silt_slate_marble",
	"goety:silt_studded_crag_tiles",
	"goety:siltstone",
	"goety:siltstone_bricks",
	"goety:siltstone_pavement",
	"goety:siltstone_pillar",
	"goety:siltstone_tiles",
	"goety:smooth_siltstone",
	"goety:snowy_chiseled_siltstone",
	"goety:snowy_cobbled_siltstone",
	"goety:snowy_siltstone",
	"goety:snowy_siltstone_bricks",
	"goety:snowy_siltstone_bricks_slight",
	"goety:snowy_siltstone_pillar",
	"goety:snowy_siltstone_slight",
	"goety:soiled_cobbled_end_stone",
	"goety:soiled_cobbled_end_stone_heavy",
	"goety:soiled_cobbled_end_stone_slight",
	"goety:soiled_end_basalt",
	"goety:soiled_end_basalt_bricks",
	"goety:soiled_end_basalt_slight",
	"goety:soiled_end_rock",
	"goety:soiled_end_rock_bricks",
	"goety:soiled_end_rock_chiseled",
	"goety:soiled_end_stone_bricks",
	"goety:soiled_end_stone_bricks_heavy",
	"goety:soiled_end_stone_bricks_slight",
	"goety:soiled_end_stone_tiles",
	"goety:soiled_polished_ominous_stone",
	"goety:soiled_polished_ominous_stone_heavy",
	"goety:soiled_purpur_block",
	"goety:top_soiled_end_basalt",
]
[Physics]
	#The maximum weight the block(s) can support both horizontally and vertically.
	#Range: > 0
	SupportStrength = 264060

	#Additional support strength to apply to the amount of weight the block(s) can support above when acting as a beam.
	#A value of 1.0 will allow the block(s) to support an infinite amount of weight, whereas a value of 0.0 will not apply any additional strengthening.
	#Range: 0.0 ~ 1.0
	BeamStrength = 0.97

	#The mass of the block(s), in kilograms.
	#Range: 1.0 ~ 50000.0
	Mass = 1200.0

	#Whether the block(s) can hang from other blocks for support.
	CanHang = true

	#Whether the block(s) can attach to the sides of other blocks for support.
	CanAttach = true

	#Whether the block(s) can diagonally attach to other blocks for support.
	CanAttachDiagonally = true

	#The chance the block(s) will slide after falling and landing.
	#Range: 0.0 ~ 1.0
	SlideChance = 0.5

	#An additional "dice roll" to apply to the base slide chance of the block(s), when being placed by an entity.
	#Setting a value of 1.0 means the slide chance will remain unaffected.
	#Range: 0.0 ~ 1.0
	PlacementSlideModifier = 0.0

	#A multiplier to apply to the damage caused by the block(s) when falling on entities.
	#Range: 0.0 ~ 10.0
	EntityDamageScale = 1.0

	#Whether the block(s) should break instead of falling.
	BreaksOnFalling = false

	#The maximum force the block(s) can withstand before being broken.
	#Range: > 0
	Strength = 782400

	#Whether the block(s) can be supported by liquids that are below.
	FloatsOnLiquid = false

	#This section allows you to extend the collision bounds for each specific face of the block(s).
	#Note: Directions are relative to the orientation of the block(s) (excluding vertical axis), not the world itself.
	[Physics.ExtendedCollisionBounds]
		#Fully extends the collision bounds of the block(s) in the UP direction.
		Up = false

		#Fully extends the collision bounds of the block(s) in the DOWN direction.
		Down = false

		#Fully extends the collision bounds of the block(s) in the NORTH direction.
		North = false

		#Fully extends the collision bounds of the block(s) in the EAST direction.
		East = false

		#Fully extends the collision bounds of the block(s) in the SOUTH direction.
		South = false

		#Fully extends the collision bounds of the block(s) in the WEST direction.
		West = false

[ChunkAnalysis]
	#Whether the block(s) should be processed during chunk analysis updates.
	Enabled = true
