#A list of block IDs and tags that should be affected by this definition.
#Entries can be supplied in the below formats:
#	Namespaces:   '<minecraft>'
#	Tags:         '#forge:stone'
#	IDs:          'minecraft:stone'
Blocks = ["aether:ambrosium_ore", "aether:gravitite_ore", "aether:holystone", "aether:mossy_holystone", "aether:zanite_ore", "create:deepslate_zinc_ore", "create:zinc_ore", "goety:cragrocks", "goety:highrock", "goety:jade_ore", "goety:ominous_stone", "hexerei:selenite_block", "malum:blazing_quartz_ore", "malum:brilliant_deepslate", "malum:brilliant_stone", "malum:cthonic_gold_ore", "malum:deepslate_quartz_ore", "malum:deepslate_soulstone_ore", "malum:natural_quartz_ore", "malum:soulstone_ore", "minecraft:amethyst_block", "minecraft:budding_amethyst", "minecraft:calcite", "minecraft:coal_ore", "minecraft:copper_ore", "minecraft:deepslate", "minecraft:deepslate_coal_ore", "minecraft:deepslate_copper_ore", "minecraft:deepslate_diamond_ore", "minecraft:deepslate_emerald_ore", "minecraft:deepslate_gold_ore", "minecraft:deepslate_iron_ore", "minecraft:deepslate_lapis_ore", "minecraft:deepslate_redstone_ore", "minecraft:diamond_ore", "minecraft:dripstone_block", "minecraft:emerald_ore", "minecraft:gold_ore", "minecraft:infested_deepslate", "minecraft:infested_stone", "minecraft:iron_ore", "minecraft:lapis_ore", "minecraft:polished_deepslate", "minecraft:raw_copper_block", "minecraft:raw_gold_block", "minecraft:raw_iron_block", "minecraft:redstone_ore", "minecraft:stone", "minecraft:tuff", "natures_spirit:chert_coal_ore", "natures_spirit:chert_copper_ore", "natures_spirit:chert_diamond_ore", "natures_spirit:chert_emerald_ore", "natures_spirit:chert_gold_ore", "natures_spirit:chert_iron_ore", "natures_spirit:chert_lapis_ore", "natures_spirit:chert_redstone_ore", "occultism:iesnium_ore", "occultism:silver_ore", "occultism:silver_ore_deepslate", "pneumaticcraft:compressed_stone", "pneumaticcraft:reinforced_stone", "quark:jasper", "quark:limestone", "quark:myalite", "quark:permafrost", "quark:polished_calcite", "quark:polished_jasper", "quark:polished_limestone", "quark:polished_myalite", "quark:polished_shale", "quark:shale", "realistic_ores:black_shale", "realistic_ores:brassroot", "realistic_ores:coal_measures", "realistic_ores:copper_bloom", "realistic_ores:deepslate_black_shale", "realistic_ores:deepslate_brassroot", "realistic_ores:deepslate_coal_measures", "realistic_ores:deepslate_copper_bloom", "realistic_ores:deepslate_evaporite_beds", "realistic_ores:deepslate_hotstone", "realistic_ores:deepslate_ironstone", "realistic_ores:deepslate_tin_quartz", "realistic_ores:evaporite_beds", "realistic_ores:hotstone", "realistic_ores:ironstone", "realistic_ores:tin_quartz", "tconstruct:cobalt_ore", "unearthed:beige_limestone_coal_ore", "unearthed:beige_limestone_copper_ore", "unearthed:beige_limestone_diamond_ore", "unearthed:beige_limestone_emerald_ore", "unearthed:beige_limestone_gold_ore", "unearthed:beige_limestone_iron_ore", "unearthed:beige_limestone_lapis_ore", "unearthed:beige_limestone_redstone_ore", "unearthed:conglomerate_coal_ore", "unearthed:conglomerate_copper_ore", "unearthed:conglomerate_diamond_ore", "unearthed:conglomerate_emerald_ore", "unearthed:conglomerate_gold_ore", "unearthed:conglomerate_iron_ore", "unearthed:conglomerate_lapis_ore", "unearthed:conglomerate_redstone_ore", "unearthed:gabbro_coal_ore", "unearthed:gabbro_copper_ore", "unearthed:gabbro_diamond_ore", "unearthed:gabbro_emerald_ore", "unearthed:gabbro_gold_ore", "unearthed:gabbro_iron_ore", "unearthed:gabbro_lapis_ore", "unearthed:gabbro_redstone_ore", "unearthed:granodiorite_coal_ore", "unearthed:granodiorite_copper_ore", "unearthed:granodiorite_diamond_ore", "unearthed:granodiorite_emerald_ore", "unearthed:granodiorite_gold_ore", "unearthed:granodiorite_iron_ore", "unearthed:granodiorite_lapis_ore", "unearthed:granodiorite_redstone_ore", "unearthed:grey_limestone_coal_ore", "unearthed:grey_limestone_copper_ore", "unearthed:grey_limestone_diamond_ore", "unearthed:grey_limestone_emerald_ore", "unearthed:grey_limestone_gold_ore", "unearthed:grey_limestone_iron_ore", "unearthed:grey_limestone_lapis_ore", "unearthed:grey_limestone_redstone_ore", "unearthed:limestone_coal_ore", "unearthed:limestone_copper_ore", "unearthed:limestone_diamond_ore", "unearthed:limestone_emerald_ore", "unearthed:limestone_gold_ore", "unearthed:limestone_iron_ore", "unearthed:limestone_lapis_ore", "unearthed:limestone_redstone_ore", "unearthed:mudstone_coal_ore", "unearthed:mudstone_copper_ore", "unearthed:mudstone_diamond_ore", "unearthed:mudstone_emerald_ore", "unearthed:mudstone_gold_ore", "unearthed:mudstone_iron_ore", "unearthed:mudstone_lapis_ore", "unearthed:mudstone_redstone_ore", "unearthed:phyllite_coal_ore", "unearthed:phyllite_copper_ore", "unearthed:phyllite_diamond_ore", "unearthed:phyllite_emerald_ore", "unearthed:phyllite_gold_ore", "unearthed:phyllite_iron_ore", "unearthed:phyllite_lapis_ore", "unearthed:phyllite_redstone_ore", "unearthed:rhyolite_coal_ore", "unearthed:rhyolite_copper_ore", "unearthed:rhyolite_diamond_ore", "unearthed:rhyolite_emerald_ore", "unearthed:rhyolite_gold_ore", "unearthed:rhyolite_iron_ore", "unearthed:rhyolite_lapis_ore", "unearthed:rhyolite_redstone_ore", "unearthed:sandstone_coal_ore", "unearthed:sandstone_copper_ore", "unearthed:sandstone_diamond_ore", "unearthed:sandstone_emerald_ore", "unearthed:sandstone_gold_ore", "unearthed:sandstone_iron_ore", "unearthed:sandstone_lapis_ore", "unearthed:sandstone_redstone_ore", "unearthed:siltstone_coal_ore", "unearthed:siltstone_copper_ore", "unearthed:siltstone_diamond_ore", "unearthed:siltstone_emerald_ore", "unearthed:siltstone_gold_ore", "unearthed:siltstone_iron_ore", "unearthed:siltstone_lapis_ore", "unearthed:siltstone_redstone_ore", "unearthed:slate_coal_ore", "unearthed:slate_copper_ore", "unearthed:slate_diamond_ore", "unearthed:slate_emerald_ore", "unearthed:slate_gold_ore", "unearthed:slate_iron_ore", "unearthed:slate_lapis_ore", "unearthed:slate_redstone_ore", "unearthed:white_granite_coal_ore", "unearthed:white_granite_copper_ore", "unearthed:white_granite_diamond_ore", "unearthed:white_granite_emerald_ore", "unearthed:white_granite_gold_ore", "unearthed:white_granite_iron_ore", "unearthed:white_granite_lapis_ore", "unearthed:white_granite_redstone_ore"]

[Physics]
	#The maximum weight the block(s) can support both horizontally and vertically.
	#Range: > 0
	SupportStrength = 146700

	#Additional support strength to apply to the amount of weight the block(s) can support above when acting as a beam.
	#A value of 1.0 will allow the block(s) to support an infinite amount of weight, whereas a value of 0.0 will not apply any additional strengthening.
	#Range: 0.0 ~ 1.0
	BeamStrength = 0.9

	#The mass of the block(s), in kilograms.
	#Range: 1.0 ~ 50000.0
	Mass = 1600.0

	#Whether the block(s) can hang from other blocks for support.
	CanHang = true

	#Whether the block(s) can attach to the sides of other blocks for support.
	CanAttach = true

	#Whether the block(s) can diagonally attach to other blocks for support.
	CanAttachDiagonally = true

	#The chance the block(s) will slide after falling and landing.
	#Range: 0.0 ~ 1.0
	SlideChance = 0.5

	#An additional "dice roll" to apply to the base slide chance of the block(s), when being placed by an entity.
	#Setting a value of 1.0 means the slide chance will remain unaffected.
	#Range: 0.0 ~ 1.0
	PlacementSlideModifier = 0.0

	#A multiplier to apply to the damage caused by the block(s) when falling on entities.
	#Range: 0.0 ~ 10.0
	EntityDamageScale = 1.0

	#Whether the block(s) should break instead of falling.
	BreaksOnFalling = false

	#The maximum force the block(s) can withstand before being broken.
	#Range: > 0
	Strength = 1124700

	#Whether the block(s) can be supported by liquids that are below.
	FloatsOnLiquid = false

	#This section allows you to extend the collision bounds for each specific face of the block(s).
	#Note: Directions are relative to the orientation of the block(s) (excluding vertical axis), not the world itself.
	[Physics.ExtendedCollisionBounds]
		#Fully extends the collision bounds of the block(s) in the UP direction.
		Up = false

		#Fully extends the collision bounds of the block(s) in the DOWN direction.
		Down = false

		#Fully extends the collision bounds of the block(s) in the NORTH direction.
		North = false

		#Fully extends the collision bounds of the block(s) in the EAST direction.
		East = false

		#Fully extends the collision bounds of the block(s) in the SOUTH direction.
		South = false

		#Fully extends the collision bounds of the block(s) in the WEST direction.
		West = false

[ChunkAnalysis]
	#Whether the block(s) should be processed during chunk analysis updates.
	Enabled = true

