// Generic construction ingredients are the default. Only these exact, reviewed
// rock-identity recipes are exempt from stone/cobblestone substitution. Do not
// whitelist functional recipes: unlisted machinery, tools, and future generic
// uses must keep accepting variants without requiring catalogue maintenance.
var BC_ROCK_IDENTITY_RECIPES = [
    // Vanilla rock families: shaping, masonry, mossing, and thermal conversion.
    'minecraft:andesite',
    'minecraft:diorite',
    'minecraft:stone',
    'minecraft:smooth_stone',
    'minecraft:stone_bricks',
    'minecraft:stone_bricks_from_stone_stonecutting',
    'minecraft:chiseled_stone_bricks_stone_from_stonecutting',
    'minecraft:stone_slab',
    'minecraft:stone_slab_from_stone_stonecutting',
    'minecraft:stone_stairs',
    'minecraft:stone_stairs_from_stone_stonecutting',
    'minecraft:stone_brick_slab_from_stone_stonecutting',
    'minecraft:stone_brick_stairs_from_stone_stonecutting',
    'minecraft:stone_brick_walls_from_stone_stonecutting',
    'minecraft:cobblestone_slab',
    'minecraft:cobblestone_slab_from_cobblestone_stonecutting',
    'minecraft:cobblestone_stairs',
    'minecraft:cobblestone_stairs_from_cobblestone_stonecutting',
    'minecraft:cobblestone_wall',
    'minecraft:cobblestone_wall_from_cobblestone_stonecutting',
    'minecraft:mossy_cobblestone_from_moss_block',
    'minecraft:mossy_cobblestone_from_vine',
    'minecraft:stone_button',
    'minecraft:stone_pressure_plate',
    // Geological reconstruction must retain the authored host rock.
    'better_ore_geology:crafting/ore_reassembly/black_shale',
    'better_ore_geology:crafting/ore_reassembly/brassroot',
    'better_ore_geology:crafting/ore_reassembly/coal_measures',
    'better_ore_geology:crafting/ore_reassembly/copper_bloom',
    'better_ore_geology:crafting/ore_reassembly/evaporite_beds',
    'better_ore_geology:crafting/ore_reassembly/hotstone',
    'better_ore_geology:crafting/ore_reassembly/ironstone',
    'better_ore_geology:crafting/ore_reassembly/tin_quartz',
    'unearthed:stone_from_stones',
    'unearthed:stone_regolith',
    'natures_spirit:travertine_from_calcite',
    // Material-specific decoration and derived stone blocks.
    'adchimneys:cobblestone_chimney',
    'adchimneys:stone_chimney',
    'alexscaves:radrock',
    'ars_nouveau:sourcestone',
    'born_in_chaos_v1:webbed_cobblestone_craft',
    'cataclysm:azure_seastone',
    'cataclysm:stone_pillar',
    'cataclysm:stonecutting/chiseled_stone_brick_pillar_from_stonecutting',
    'cataclysm:stonecutting/stone_pillar_from_stonecutting',
    'cataclysm:stonecutting/stone_tile_slab_from_stonecutting',
    'cataclysm:stonecutting/stone_tile_stairs_from_stonecutting',
    'cataclysm:stonecutting/stone_tile_wall_from_stonecutting',
    'cataclysm:stonecutting/stone_tiles_from_stonecutting',
    'dawnoftimebuilder:amethyst_feathered_serpent_sculpture',
    'dawnoftimebuilder:amethyst_serpent_scultped_column',
    'dawnoftimebuilder:blue_painted_stone',
    'dawnoftimebuilder:blue_plastered_stone',
    'dawnoftimebuilder:feathered_serpent_sculpture',
    'dawnoftimebuilder:gold_plated_smooth_block',
    'dawnoftimebuilder:green_painted_stone',
    'dawnoftimebuilder:green_plastered_stone',
    'dawnoftimebuilder:moraq_mosaic_recess',
    'dawnoftimebuilder:ochre_roof_tiles',
    'dawnoftimebuilder:plastered_stone',
    'dawnoftimebuilder:red_painted_stone',
    'dawnoftimebuilder:red_plastered_stone',
    'dawnoftimebuilder:serpent_sculpted_column',
    'dawnoftimebuilder:silver_feathered_serpent_sculpture',
    'dawnoftimebuilder:silver_serpent_scultped_column',
    'dawnoftimebuilder:stepping_stones',
    'dawnoftimebuilder:stepping_stones_slab',
    'dawnoftimebuilder:stone_bricks_masonry',
    'dawnoftimebuilder:white_painted_stone',
    'dawnoftimebuilder:yellow_painted_stone',
    'dawnoftimebuilder:yellow_plastered_stone',
    'framedblocks:framed_stone_button',
    'framedblocks:framed_stone_pressure_plate',
    'goety:cobbled_dark_dirt',
    'goety:cobbled_dirt',
    'goety:highrock/highrock',
    'goety:ominous/ominous_stone',
    'goety:shade/shade_stone',
    'goety:shade/shade_stone_craft',
    'goety:snow_bricks/snow_bricks',
    'goety:stone_throne',
    'hexerei:stone_window',
    'iceandfire:dread_stone',
    'quark:building/crafting/cobblestone_bricks',
    'quark:building/crafting/sturdy_stone',
    'quark:building/stonecutting/cobblestone_bricks_stonecutter',
    'quark:building/stonecutting/vertslabs/cobblestone_vertical_slab_stonecutter',
    'quark:building/stonecutting/vertslabs/stone_brick_vertical_slab_stonecutter',
    'quark:building/stonecutting/vertslabs/stone_vertical_slab_stonecutter',
    'twilightforest:stonecutting/stone/bold_stone_pillar',
    'twilightforest:stonecutting/stone/twisted_stone',
    // Material conversion/finishing, rather than generic machinery or reagents.
    'bloodmagic:altar/slate',
    'bloodmagic:arc/mossify_cobblestone',
    'bloodmagic:array/spike',
    'bloodmagic:dungeon_stone',
    'bloodmagic:dungeon_stone_corrosive',
    'bloodmagic:dungeon_stone_corrosive_spread',
    'bloodmagic:dungeon_stone_destructive',
    'bloodmagic:dungeon_stone_destructive_spread',
    'bloodmagic:dungeon_stone_spread',
    'bloodmagic:dungeon_stone_steadfast',
    'bloodmagic:dungeon_stone_steadfast_spread',
    'bloodmagic:dungeon_stone_vengeful',
    'bloodmagic:dungeon_stone_vengeful_spread',
    'bloodmagic:largebloodstonebrick',
    'bloodmagic:path/path_stone',
    'create:haunting/blackstone',
    'create:haunting/infested_stone',
    'immersive_weathering:mossy_cobblestone_from_moss_clump',
    'immersive_weathering:mossy_stone_from_moss_block',
    'immersive_weathering:mossy_stone_from_moss_clump',
    'immersive_weathering:mossy_stone_from_vine',
    'immersive_weathering:stone_brick_from_cobblestone_stonecutting',
    'immersive_weathering:stone_brick_from_stonecutting',
    'immersive_weathering:stone_wall',
    'immersive_weathering:stone_wall_from_stonecutting',
    'malum:netherrack_from_blazing_quartz',
    'occultism:spirit_trade/stone_to_otherstone',
    'occultism:spirit_trade/test',
    'pneumaticcraft:pressure_chamber/compressed_stone',
    'pneumaticcraft:reinforced_stone',
    'pneumaticcraft:stone_base',
    'tconstruct:smeltery/casting/quartz/andesite',
    'tconstruct:smeltery/casting/seared/cobble/block',
    'tconstruct:smeltery/casting/seared/stone/block_from_clay',
    'upgrade_aquatic:kelpy_cobblestone'
]

ServerEvents.recipes(function (event) {
    // KubeJS RecipeFilter parses the string array as OR of exact IDs; not
    // excludes that identity whitelist while leaving all other uses generic.
    var genericRockUses = { not: BC_ROCK_IDENTITY_RECIPES }
    event.replaceInput(genericRockUses, 'minecraft:stone', '#forge:stone')
    event.replaceInput(genericRockUses, 'minecraft:cobblestone', '#forge:cobblestone')
    event.shaped('minecraft:furnace', [
        'SSS',
        'S S',
        'SSS'
    ], {
        S: '#kubejs:furnace_materials'
    }).id('kubejs:crafting/furnace_from_stone_or_cobblestone')
})
